# Uncomment the following lines to enable RGB underglow
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_EXT_POWER=y
# ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y
CONFIG_ZMK_SPLIT=y
# CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n is set per-build via cmake-args in build.yaml
